apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: alert-tests
    role: alert-rules
    app: prometheus-operator
    release: prometheus-operator
  name: prometheus-alert-tests
spec:
  groups:
  - name: alert-tests.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
    - alert: ExampleAlert2
      expr: vector(1)
    - alert: NodeGreyFailure # EHashman's example, may need to adjust for what's unusual 
      expr: scrape_duration_seconds{job="node"} > 2