#alertmanager configuration secret
#kubectl create secret generic alertmanager-prometheus-operator-alertmanager --from-file=alertmanager.yaml --dry-run -o yaml | kubectl apply -f -
#To-do: Pipeline this?
#Question: Should the above be create --save-config?
#Question: Is there a better way to update this? 
#Question: Is there a way to specify a different expected configuration filename? 'alertmanager.yaml' is ambiguous.
global:
  resolve_timeout: 5m
receivers:
- name: cloud_slack
  slack_configs:
  - api_url: '[webhook goes here]' 
  #TO-DO/QUESTION: How to load the webhook from a secret?
  #Assuming https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
  #But not sure how to configure on the operator...
    channel: '#prometheus-alerts'
- name: black_hole #Empty default receiver
#To do: instead configure Prometheus to not send low/info-severity to AlertManager. Ref: https://github.com/prometheus/alertmanager/issues/428#issuecomment-468952018
route:
  group_by: [cluster, alertname]
  group_interval: 5m
  group_wait: 30s
  receiver: black_hole
  repeat_interval: 300h #Shhh
  routes:
  - match:
      severity: slack
    receiver: cloud_slack