apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: management-platform-alerts
    role: management-platform-alert-rules
    app: kube-prometheus-stack
    release: kube-prometheus-stack
  name: management-platform-alerts
spec:
  groups:
  - name: management.rules
    rules:
    - alert: BackupJobFailed
      expr: sum by (job_name,namespace) (kube_job_failed{job_name=~".*backup.*"}) == 1
      for: 2m
      labels:
        severity: urgent
        resolves: never
        scope: platform
      annotations:
        message: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.  Removing the failed job after investigation should clear this alert.'
