apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: supercritical-alerts
    role: supercritical-alert-rules
    app: prometheus-operator
    release: prometheus-operator
  name: prometheus-supercritical-alerts
spec:
  groups:
  - name: supercritical-node-alerts.rules
    rules:
    - alert: NodeDiskPressure
      expr: kube_node_status_condition{condition="DiskPressure",job="kube-state-metrics",status="true"} == 1
      for: 2m
      labels:
        severity: supercritical
      annotations:
        message: "{{ $labels.node }} has low disk capacity."
    - alert: NodeMemoryPressure
      expr: kube_node_status_condition{condition="MemoryPressure",job="kube-state-metrics",status="true"} == 1
      for: 2m
      labels:
        severity: supercritical
      annotations:
        message: "{{ $labels.node }} has low memory."
    - alert: NodePIDPressure
      expr: kube_node_status_condition{condition="PIDPressure",job="kube-state-metrics",status="true"} == 1
      for: 2m
      labels:
        severity: supercritical
      annotations:
        message: "Too many processes are running on {{ $labels.node }}."
    - alert: NodeNetworkUnavailable
      expr: kube_node_status_condition{condition="NetworkUnavailable",job="kube-state-metrics",status="true"} == 1
      for: 2m
      labels:
        severity: supercritical
      annotations:
        message: "The network for {{ $labels.node }} is not correctly configured."
    - alert: NodeNotReady
      expr: kube_node_status_condition{condition="Ready",job="kube-state-metrics",status="true"} == 0
      for: 2m
      labels:
        severity: supercritical
      annotations:
        message: "{{ $labels.node }} is not in a Ready state but did not trip a Network or Pressure condition."
    - alert: NodeUnscheduleable
      expr: kube_node_spec_unschedulable{job="kube-state-metrics"} == 1
      for: 1h
      labels:
        severity: supercritical
      annotations:
        message: "{{ $labels.node }} is unscheduleable for over 1 hour. If it is healthy, is it cordoned?"

