#alertmanager configuration secret
#kubectl create secret generic alertmanager-prometheus-operator-alertmanager --from-file=alertmanager.yaml --dry-run -o yaml | kubectl apply -f -
#To-do: Pipeline this?
global:
  resolve_timeout: 5m
receivers:
- name: cloud_slack
  slack_configs: 
  - api_url: {{ .Values.cloud_slack_incoming_webhook | squote }}
    channel: '#prometheus-alerts'
- name: black_hole #Empty default receiver
# To do: instead configure Prometheus to not send low/info-severity to AlertManager.
# Ref: https://github.com/prometheus/alertmanager/issues/428#issuecomment-468952018
route:
  group_by: [cluster, alertname]
  group_interval: 5m
  group_wait: 30s
  receiver: black_hole
  repeat_interval: 24h
  routes:
  - match:
      severity: critical
    receiver: cloud_slack