#alertmanager configuration secret
#To-do: Pipeline this
global:
  resolve_timeout: 5m
receivers:
- name: cloud_slack
  slack_configs: 
  - api_url: {{ .Values.cloud_slack_incoming_webhook | squote }}
    channel: '#prometheus-alerts'
    send_resolved: true
    title: {{`'{{ template "slack.slackcustom.title" . }}'`}}
    text: {{`'{{ template "slack.slackcustom.text" . }}'`}}
- name: black_hole #Empty default receiver
# To do: come up with a low/info-severity route, or else configure Prometheus to not send low/info-severity to AlertManager.
# Ref: https://github.com/prometheus/alertmanager/issues/428#issuecomment-468952018
route:
  group_by: ['alertname', 'job']
  group_interval: 10m
  group_wait: 45s
  receiver: black_hole
  repeat_interval: 1w
  routes:
  - match:
      severity: critical
    receiver: cloud_slack
templates:
- '*.tmpl'
